;;;; -*- Mode: Lisp; Syntax: ANSI-Common-Lisp; Base: 10 -*-
;;;; See the LICENSE file for licensing information.

(in-package #:cl-user)


(defpackage #:cl-poppler-ffi
  (:nicknames #:poppler)
  (:use :cl :cffi :babel)
  (:import-from :cl-poppler-ffi-asd :*poppler-version*)
  (:export ())
  (:documentation
   "Common Lisp FFI for @em{Poppler}, PDF using QT4

    @begin[About]{section}

    About cl-poppler-ffi

    @end{section}

    @begin[Documentation]{section}

    This documentation was generated by @a[http://www.lichteblau.com/atdoc/doc/]{atdoc},
    the documentation generation system written by David Lichteblau.

    @end{section}
"))

